# Generated by Django 3.2.6 on 2021-08-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('stena', '0002_auto_20210809_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='mes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notes',
                                    to='stena.category', verbose_name='Категория'),
        ),
    ]
