# Generated by Django 3.2.7 on 2021-09-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stena', '0003_auto_20210821_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mes',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Заголовок'),
        ),
    ]
